export const WELCOME_TEXT = 'Welcome to Spatial Quality!';
export const JOIN_PROJECT = 'Join project';
export const PLACE_GENERAL_PIN = 'Place general pin';
export const GENERAL_FORM_HEADER = 'We are more than happy to hear from you!';
export const EXPLANATION_PARAGRAPH = 'We are happy to help you give your opinion about all the different locations around the Netherlands. To do that, enter an access code to participate on a project, or place a general pin anywhere around the country, by clicking \'' + PLACE_GENERAL_PIN + '\'';
export const ACCESS_CODE_PLACEHOLDER = 'Enter the code';
export const ACCESS_CODE_LABEL = 'Access code';
export const PARTICIPATE = 'Participate';
export const PIN_ADDRESS_PLACEHOLDER = 'Click on the map to select an address';
